"""AuthClaw Python SDK public contract package."""

from .client import AuthClawClient
from .auth import (
    ApiKeyManager,
    build_authenticated_headers,
    build_default_headers,
)
from .client_contracts import (
    ApiKeyConfigurationContract,
    ChatCompletionRequestContract,
    ChatCompletionResponseContract,
    ClientContract,
    RetryConfigurationContract,
    SdkMetadataContract,
    StreamingRequestContract,
    StreamingResponseContract,
    TimeoutConfigurationContract,
)
from .config import AuthClawConfig
from .exceptions import (
    AuthClawError,
    AuthenticationError,
    AuthorizationError,
    ConfigurationError,
    ConnectionError,
    RateLimitError,
    ServerError,
    StreamingError,
    TimeoutError,
    ValidationError,
)
from .models import (
    ChatCompletionChoice,
    ChatMessage,
    GatewayMetadata,
    RequestOptions,
    StreamingDelta,
    UsageMetadata,
)
from .types import (
    FinishReason,
    MessageRole,
    RedactionMode,
    ResponseFormat,
    RetryBackoff,
    SdkTransport,
    StreamEventType,
)
from .retry import (
    RetryContext,
    RetryDecision,
    RetryPolicy,
    RetryStrategy,
)
from .streaming import (
    SdkSseParser,
    SseEvent,
    StreamingClient,
    StreamingResponseIterator,
)
from .transport import (
    MockTransport,
    RequestsTransport,
    Transport,
    TransportRequest,
    TransportResponse,
    TransportStreamResponse,
    dumps_json,
)
from .version import (
    MINIMUM_AUTHCLAW_VERSION,
    SDK_VERSION,
    SUPPORTED_API_VERSION,
    SdkVersionContract,
    get_version,
)

__all__ = [
    "ApiKeyConfigurationContract",
    "ApiKeyManager",
    "AuthClawError",
    "AuthClawClient",
    "AuthClawConfig",
    "AuthenticationError",
    "AuthorizationError",
    "ChatCompletionChoice",
    "ChatCompletionRequestContract",
    "ChatCompletionResponseContract",
    "ChatMessage",
    "ClientContract",
    "ConfigurationError",
    "ConnectionError",
    "FinishReason",
    "GatewayMetadata",
    "MINIMUM_AUTHCLAW_VERSION",
    "MessageRole",
    "MockTransport",
    "RateLimitError",
    "RedactionMode",
    "RequestOptions",
    "ResponseFormat",
    "RetryBackoff",
    "RetryConfigurationContract",
    "RetryContext",
    "RetryDecision",
    "RetryPolicy",
    "RetryStrategy",
    "RequestsTransport",
    "SDK_VERSION",
    "SUPPORTED_API_VERSION",
    "SdkMetadataContract",
    "SdkTransport",
    "SdkVersionContract",
    "ServerError",
    "SdkSseParser",
    "StreamEventType",
    "StreamingDelta",
    "StreamingClient",
    "StreamingError",
    "StreamingRequestContract",
    "StreamingResponseContract",
    "StreamingResponseIterator",
    "SseEvent",
    "TimeoutConfigurationContract",
    "TimeoutError",
    "Transport",
    "TransportRequest",
    "TransportResponse",
    "TransportStreamResponse",
    "UsageMetadata",
    "ValidationError",
    "build_authenticated_headers",
    "build_default_headers",
    "dumps_json",
    "get_version",
]
