import uuid
from datetime import datetime
from sqlalchemy import Column, String, DateTime, ForeignKey, Text, Enum
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
import enum

from app.models.base import Base


class ApprovalStatus(str, enum.Enum):
    """Lifecycle states of an approval request."""
    pending = "pending"
    approved = "approved"
    rejected = "rejected"
    executed = "executed"
    failed = "failed"
    expired = "expired"   # Added: approval TTL has passed without action


class ApprovalActionType(str, enum.Enum):
    """Category of the remediation action being approved."""
    terraform = "terraform"
    cli = "cli"
    config = "config"


class Approval(Base):
    """
    A Human-In-The-Loop approval request generated by the agent engine.

    Security Properties
    -------------------
    * Non-transferable : `requested_by_user_id` records who created the request;
                         only that user (or an Admin/Owner) may approve it.
    * Expiring         : `expires_at` enforces a 30-minute TTL; the approval
                         endpoint transitions the status to `expired` when this
                         timestamp is exceeded.
    * Single-use       : Only `pending` approvals may transition to another state.
    """
    __tablename__ = "approvals"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    tenant_id = Column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )

    # Who requested this approval — used for non-transferable enforcement
    requested_by_user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )

    title = Column(String, nullable=False)
    description = Column(Text, nullable=False)

    action_type = Column(Enum(ApprovalActionType), nullable=False)
    status = Column(Enum(ApprovalStatus), default=ApprovalStatus.pending, nullable=False)

    diff_content = Column(Text, nullable=True)  # E.g. terraform plan output or CLI script

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    expires_at = Column(DateTime, nullable=True)   # 30-minute TTL, set by agent at creation
    resolved_at = Column(DateTime, nullable=True)

    tenant = relationship("Tenant", backref="approvals")
    requested_by = relationship("User", foreign_keys=[requested_by_user_id])
