"""
AuthClaw Sprint 2 — CloudIntegration Model
------------------------------------------
Stores per-tenant cloud provider integrations (AWS / GitHub / GCP).

Design principles:
  • Raw credentials NEVER stored here.  The `vault_reference_id` field holds
    the Vault KV path where the envelope-encrypted credential blob lives.
  • Every row is scoped to a single tenant_id — the gateway enforces this at
    the query level (RLS + application-layer WHERE clause).
  • Status transitions:
      PENDING   → integration created, validation not yet run
      ACTIVE    → credential validated, syncing normally
      ERROR     → last sync or validation failed; error_message explains why
      SYNCING   → a ConnectorWorker currently holds the distributed lock
      DISABLED  → tenant manually disabled this integration
"""
from __future__ import annotations

import enum
import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import (
    Enum as SAEnum,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, UUIDMixin, TimestampMixin


class CloudProvider(str, enum.Enum):
    """Supported cloud / source-control providers."""
    aws    = "aws"
    github = "github"
    gcp    = "gcp"
    azure  = "azure"


class IntegrationStatus(str, enum.Enum):
    """Lifecycle states of a CloudIntegration record."""
    pending  = "pending"   # Created; awaiting credential validation
    active   = "active"    # Validated; syncing normally
    error    = "error"     # Last sync/validation failed
    syncing  = "syncing"   # Worker holds the distributed lock right now
    disabled = "disabled"  # Manually disabled by tenant


class CloudIntegration(Base, UUIDMixin, TimestampMixin):
    """
    One row per tenant-cloud-account pairing.

    Tenant isolation:
      - tenant_id is indexed and enforced in every query.
      - The Vault path is scoped to the tenant:
          secret/authclaw/tenants/{tenant_id}/integrations/{id}
      - A tenant can never read another tenant's vault_reference_id because
        the id is a UUID generated by Postgres and never exposed cross-tenant.
    """
    __tablename__ = "cloud_integrations"
    __table_args__ = (
        # Fast lookup: all integrations for a tenant
        Index("idx_cloud_integrations_tenant_id", "tenant_id"),
        # Uniqueness: one integration per (tenant, provider, target)
        # e.g., a tenant can have one AWS integration per Account ID
        Index(
            "uq_cloud_integrations_tenant_provider_target",
            "tenant_id", "provider_type", "target_identifier",
            unique=True,
        ),
    )

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        comment="Owning tenant. Cascade-deleted when tenant is removed.",
    )

    provider_type: Mapped[CloudProvider] = mapped_column(
        SAEnum(CloudProvider, name="cloud_provider", create_type=True),
        nullable=False,
        comment="Cloud provider type (aws, github, gcp).",
    )

    target_identifier: Mapped[str] = mapped_column(
        String(512),
        nullable=False,
        comment=(
            "Provider-specific target. "
            "AWS: account ID. "
            "GitHub: org or org/repo. "
            "GCP: project ID."
        ),
    )

    display_name: Mapped[Optional[str]] = mapped_column(
        String(255),
        nullable=True,
        comment="Human-readable label shown in the UI.",
    )

    status: Mapped[IntegrationStatus] = mapped_column(
        SAEnum(IntegrationStatus, name="integration_status", create_type=True),
        nullable=False,
        server_default="pending",
        index=True,
        comment="Current lifecycle state of the integration.",
    )

    vault_reference_id: Mapped[str] = mapped_column(
        String(1024),
        nullable=False,
        comment=(
            "Vault KV path for this integration's credentials. "
            "Format: secret/authclaw/tenants/{tenant_id}/integrations/{id}. "
            "Raw credentials are NEVER stored in this table."
        ),
    )

    last_sync_at: Mapped[Optional[datetime]] = mapped_column(
        nullable=True,
        comment="UTC timestamp of the last successful sync.",
    )

    last_sync_finding_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
        comment="Number of findings returned by the last sync.",
    )

    error_message: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment="Last error from validation or sync. Cleared on success.",
    )

    # Relationships
    tenant = relationship("Tenant", backref="cloud_integrations")
    findings = relationship(
        "SecurityFinding",
        back_populates="integration",
        cascade="all, delete-orphan",
    )
