"""Add provider error fields to gateway request

Revision ID: 10a0152c54cc
Revises: 573213bfb84a
Create Date: 2026-06-16 09:00:08.715137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a0152c54cc'
down_revision: Union[str, None] = '573213bfb84a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateway_requests', sa.Column('provider_status_code', sa.Integer(), nullable=True))
    op.add_column('gateway_requests', sa.Column('error_type', sa.String(length=100), nullable=True))
    op.add_column('gateway_requests', sa.Column('error_code', sa.String(length=100), nullable=True))
    op.add_column('gateway_requests', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gateway_requests', 'error_message')
    op.drop_column('gateway_requests', 'error_code')
    op.drop_column('gateway_requests', 'error_type')
    op.drop_column('gateway_requests', 'provider_status_code')
    # ### end Alembic commands ###
