"""stream3_event_backbone

Revision ID: 3c81669a01f3
Revises: 69f5e88e946a
Create Date: 2026-06-17 13:03:09.138281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c81669a01f3'
down_revision: Union[str, None] = '69f5e88e946a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('consumer_group', sa.String(length=255), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('event_id', 'consumer_group', name=op.f('pk_processed_events'))
    )
    op.create_index(op.f('ix_processed_events_tenant_id'), 'processed_events', ['tenant_id'], unique=False)
    op.create_table('wal_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('payload_bytes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wal_events'))
    )
    op.create_index(op.f('ix_wal_events_status'), 'wal_events', ['status'], unique=False)
    op.create_index(op.f('ix_wal_events_topic'), 'wal_events', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wal_events_topic'), table_name='wal_events')
    op.drop_index(op.f('ix_wal_events_status'), table_name='wal_events')
    op.drop_table('wal_events')
    op.drop_index(op.f('ix_processed_events_tenant_id'), table_name='processed_events')
    op.drop_table('processed_events')
    # ### end Alembic commands ###
