"""add_rate_limit_event

Revision ID: 432aefdda0c7
Revises: 4ffee7ad38f6
Create Date: 2026-06-18 05:54:08.983479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '432aefdda0c7'
down_revision: Union[str, None] = '4ffee7ad38f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE event_type ADD VALUE IF NOT EXISTS 'gateway.rate_limit.exceeded';")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
