"""stream4_audit_integrity

Revision ID: 4ffee7ad38f6
Revises: 3c81669a01f3
Create Date: 2026-06-18 05:01:19.370893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ffee7ad38f6'
down_revision: Union[str, None] = '3c81669a01f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('previous_hash', sa.String(length=64), nullable=True))
    op.add_column('audit_logs', sa.Column('hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'hash')
    op.drop_column('audit_logs', 'previous_hash')
    # ### end Alembic commands ###
