"""add_oidc_mapping_tables

Revision ID: 69f5e88e946a
Revises: c1a2b3d4e5f6
Create Date: 2026-06-17 12:43:07.621941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f5e88e946a'
down_revision: Union[str, None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_domains',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_domains_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_domains'))
    )
    op.create_index(op.f('ix_tenant_domains_domain'), 'tenant_domains', ['domain'], unique=True)
    op.create_index(op.f('ix_tenant_domains_tenant_id'), 'tenant_domains', ['tenant_id'], unique=False)
    op.create_table('tenant_invites',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_tenant_invites_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_invites_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_invites'))
    )
    op.create_index(op.f('ix_tenant_invites_email'), 'tenant_invites', ['email'], unique=False)
    op.create_index(op.f('ix_tenant_invites_tenant_id'), 'tenant_invites', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_invites_token'), 'tenant_invites', ['token'], unique=True)
    op.add_column('users', sa.Column('sso_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('sso_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_sso_id'), 'users', ['sso_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_sso_id'), table_name='users')
    op.drop_column('users', 'sso_id')
    op.drop_column('users', 'sso_provider')
    op.drop_index(op.f('ix_tenant_invites_token'), table_name='tenant_invites')
    op.drop_index(op.f('ix_tenant_invites_tenant_id'), table_name='tenant_invites')
    op.drop_index(op.f('ix_tenant_invites_email'), table_name='tenant_invites')
    op.drop_table('tenant_invites')
    op.drop_index(op.f('ix_tenant_domains_tenant_id'), table_name='tenant_domains')
    op.drop_index(op.f('ix_tenant_domains_domain'), table_name='tenant_domains')
    op.drop_table('tenant_domains')
    # ### end Alembic commands ###
