"""Add groq to provider type

Revision ID: 988b8a7b9556
Revises: a73bc3de0931
Create Date: 2026-06-17 07:30:23.844554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '988b8a7b9556'
down_revision: Union[str, None] = 'a73bc3de0931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE provider_type ADD VALUE IF NOT EXISTS 'groq'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
