"""add_stream_events

Revision ID: c8d6607bff04
Revises: 432aefdda0c7
Create Date: 2026-06-18 06:08:42.709711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8d6607bff04'
down_revision: Union[str, None] = '432aefdda0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE event_type ADD VALUE IF NOT EXISTS 'gateway.stream.started';")
    op.execute("ALTER TYPE event_type ADD VALUE IF NOT EXISTS 'gateway.stream.completed';")
    op.execute("ALTER TYPE event_type ADD VALUE IF NOT EXISTS 'gateway.stream.failed';")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
