"""Initial

Revision ID: d1b5cf1211e5
Revises: 
Create Date: 2026-06-12 15:18:53.015441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1b5cf1211e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.Enum('free', 'starter', 'professional', 'enterprise', name='tenant_plan'), server_default='free', nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'deactivated', name='tenant_status'), server_default='active', nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_table('compliance_scores',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('framework', sa.Enum('gdpr', 'hipaa', 'soc2', 'iso27001', 'iso42001', 'eu_ai_act', name='compliance_framework'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('critical_violations', sa.Integer(), server_default='0', nullable=False),
    sa.Column('policy_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('security_findings', sa.Integer(), server_default='0', nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_compliance_scores_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_scores'))
    )
    op.create_index('idx_compliance_calculated', 'compliance_scores', ['tenant_id', 'calculated_at'], unique=False, postgresql_using='btree')
    op.create_index('idx_compliance_framework', 'compliance_scores', ['tenant_id', 'framework'], unique=False)
    op.create_index(op.f('ix_compliance_scores_tenant_id'), 'compliance_scores', ['tenant_id'], unique=False)
    op.create_table('permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('role_id', 'resource', 'action', name='uq_permissions_role_resource_action')
    )
    op.create_table('policies',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_policies_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies'))
    )
    op.create_index('idx_policies_active', 'policies', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_policies_tenant_id'), 'policies', ['tenant_id'], unique=False)
    op.create_table('providers',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('openai', 'anthropic', 'gemini', 'cohere', 'azure_openai', name='provider_type'), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_providers_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_providers'))
    )
    op.create_index(op.f('ix_providers_tenant_id'), 'providers', ['tenant_id'], unique=False)
    op.create_table('settings',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_settings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings')),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_settings_tenant_key')
    )
    op.create_index(op.f('ix_settings_tenant_id'), 'settings', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.Enum('full', 'gateway_only', 'read_only', name='api_key_scope'), server_default='full', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_api_keys_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('auth_login', 'auth_logout', 'auth_signup', 'auth_password_reset', 'gateway_request', 'gateway_response', 'gateway_blocked', 'policy_violation', 'policy_created', 'policy_updated', 'policy_deleted', 'compliance_score_calculated', 'admin_user_created', 'admin_user_updated', 'admin_role_changed', 'admin_provider_created', 'admin_provider_updated', 'approval_requested', 'approval_approved', 'approval_rejected', name='event_type'), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.Enum('create', 'read', 'update', 'delete', 'execute', name='audit_action'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_logs_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('idx_audit_created', 'audit_logs', ['tenant_id', 'created_at'], unique=False, postgresql_using='btree')
    op.create_index('idx_audit_event', 'audit_logs', ['tenant_id', 'event_type'], unique=False)
    op.create_index('idx_audit_resource', 'audit_logs', ['tenant_id', 'resource', 'resource_id'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['tenant_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('gateway_requests',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_original', sa.Text(), nullable=False),
    sa.Column('prompt_redacted', sa.Text(), nullable=True),
    sa.Column('pii_detections', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'blocked', 'error', name='request_status'), server_default='pending', nullable=False),
    sa.Column('token_count_prompt', sa.Integer(), server_default='0', nullable=False),
    sa.Column('latency_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_gateway_requests_provider_id_providers')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_gateway_requests_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_gateway_requests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gateway_requests'))
    )
    op.create_index('idx_gw_requests_created', 'gateway_requests', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_gw_requests_status', 'gateway_requests', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_gateway_requests_tenant_id'), 'gateway_requests', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_gateway_requests_user_id'), 'gateway_requests', ['user_id'], unique=False)
    op.create_table('policy_rules',
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('rule_type', sa.Enum('pii_block', 'pii_redact', 'content_filter', 'rate_limit', 'model_restrict', 'custom', name='rule_type'), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('action', sa.Enum('allow', 'warn', 'block', name='policy_action'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_policy_rules_policy_id_policies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_rules'))
    )
    op.create_index(op.f('ix_policy_rules_policy_id'), 'policy_rules', ['policy_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_user_roles_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', 'tenant_id', name='uq_user_roles_user_role_tenant')
    )
    op.create_table('gateway_responses',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('response_original', sa.Text(), nullable=True),
    sa.Column('response_redacted', sa.Text(), nullable=True),
    sa.Column('pii_detections', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('token_count_completion', sa.Integer(), server_default='0', nullable=False),
    sa.Column('latency_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['gateway_requests.id'], name=op.f('fk_gateway_responses_request_id_gateway_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gateway_responses')),
    sa.UniqueConstraint('request_id', name=op.f('uq_gateway_responses_request_id'))
    )
    op.create_table('policy_violations',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('policy_id', sa.Uuid(), nullable=True),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='violation_severity'), server_default='medium', nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('resolution', sa.Enum('pending', 'acknowledged', 'resolved', 'false_positive', name='violation_resolution'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_policy_violations_policy_id_policies')),
    sa.ForeignKeyConstraint(['request_id'], ['gateway_requests.id'], name=op.f('fk_policy_violations_request_id_gateway_requests')),
    sa.ForeignKeyConstraint(['rule_id'], ['policy_rules.id'], name=op.f('fk_policy_violations_rule_id_policy_rules')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_policy_violations_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_violations'))
    )
    op.create_index('idx_violations_created', 'policy_violations', ['tenant_id', 'created_at'], unique=False, postgresql_using='btree')
    op.create_index('idx_violations_severity', 'policy_violations', ['tenant_id', 'severity'], unique=False)
    op.create_index(op.f('ix_policy_violations_tenant_id'), 'policy_violations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_violations_tenant_id'), table_name='policy_violations')
    op.drop_index('idx_violations_severity', table_name='policy_violations')
    op.drop_index('idx_violations_created', table_name='policy_violations', postgresql_using='btree')
    op.drop_table('policy_violations')
    op.drop_table('gateway_responses')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_policy_rules_policy_id'), table_name='policy_rules')
    op.drop_table('policy_rules')
    op.drop_index(op.f('ix_gateway_requests_user_id'), table_name='gateway_requests')
    op.drop_index(op.f('ix_gateway_requests_tenant_id'), table_name='gateway_requests')
    op.drop_index('idx_gw_requests_status', table_name='gateway_requests')
    op.drop_index('idx_gw_requests_created', table_name='gateway_requests')
    op.drop_table('gateway_requests')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_index('idx_audit_event', table_name='audit_logs')
    op.drop_index('idx_audit_created', table_name='audit_logs', postgresql_using='btree')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_settings_tenant_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_providers_tenant_id'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_policies_tenant_id'), table_name='policies')
    op.drop_index('idx_policies_active', table_name='policies')
    op.drop_table('policies')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_compliance_scores_tenant_id'), table_name='compliance_scores')
    op.drop_index('idx_compliance_framework', table_name='compliance_scores')
    op.drop_index('idx_compliance_calculated', table_name='compliance_scores', postgresql_using='btree')
    op.drop_table('compliance_scores')
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('roles')
    # ### end Alembic commands ###
